name: Lint Commit Messages
on:
  pull_request:
    types: [opened, reopened, edited, review_requested]
    
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
