name: Lint Commit Messages
on:
  pull_request:
    types: [opened, reopened, edited, review_requested, synchronize]
    
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
