name: PR
on:
  pull_request:
    types: [opened, reopened, edited, review_requested]
    
jobs:
    
  conventional:
    name: Conventional PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
             
      - name: Install dependencies
        run: npm ci
    
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
